import os

import pandas as pd
import numpy as np
import json

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, Column, Integer, Float, String
from flask_cors import CORS
from flask import Flask, jsonify, render_template

engine = create_engine("sqlite:///db/map_db.sqlite")
app = Flask(__name__)
CORS(app)

AL_df = pd.read_sql_query("select * from PollutionAL", engine)
AK_df = pd.read_sql_query("select * from PollutionAK", engine)
AZ_df = pd.read_sql_query("select * from PollutionAZ", engine)
AR_df = pd.read_sql_query("select * from PollutionAR", engine)
CA_df = pd.read_sql_query("select * from PollutionCA", engine)
CO_df = pd.read_sql_query("select * from PollutionCO", engine)
CT_df = pd.read_sql_query("select * from PollutionCT", engine)
DE_df = pd.read_sql_query("select * from PollutionDE", engine)
FL_df = pd.read_sql_query("select * from PollutionFL", engine)
GA_df = pd.read_sql_query("select * from PollutionGA", engine)
HI_df = pd.read_sql_query("select * from PollutionHI", engine)
ID_df = pd.read_sql_query("select * from PollutionID", engine)
IL_df = pd.read_sql_query("select * from PollutionIL", engine)
IA_df = pd.read_sql_query("select * from PollutionIA", engine)
KS_df = pd.read_sql_query("select * from PollutionKS", engine)
LA_df = pd.read_sql_query("select * from PollutionLA", engine)
ME_df = pd.read_sql_query("select * from PollutionME", engine)
MD_df = pd.read_sql_query("select * from PollutionMD", engine)
MA_df = pd.read_sql_query("select * from PollutionMA", engine)
MI_df = pd.read_sql_query("select * from PollutionMI", engine)
MN_df = pd.read_sql_query("select * from PollutionMN", engine)
MS_df = pd.read_sql_query("select * from PollutionMS", engine)
MO_df = pd.read_sql_query("select * from PollutionMO", engine)
MT_df = pd.read_sql_query("select * from PollutionMT", engine)
NE_df = pd.read_sql_query("select * from PollutionNE", engine)
NV_df = pd.read_sql_query("select * from PollutionNV", engine)
NJ_df = pd.read_sql_query("select * from PollutionNJ", engine)
NM_df = pd.read_sql_query("select * from PollutionNM", engine)
NY_df = pd.read_sql_query("select * from PollutionNY", engine)
NC_df = pd.read_sql_query("select * from PollutionNC", engine)
ND_df = pd.read_sql_query("select * from PollutionND", engine)
OH_df = pd.read_sql_query("select * from PollutionOH", engine)
OK_df = pd.read_sql_query("select * from PollutionOK", engine)
OR_df = pd.read_sql_query("select * from PollutionOR", engine)
PA_df = pd.read_sql_query("select * from PollutionPA", engine)
RI_df = pd.read_sql_query("select * from PollutionRI", engine)
SC_df = pd.read_sql_query("select * from PollutionSC", engine)
SD_df = pd.read_sql_query("select * from PollutionSD", engine)
TN_df = pd.read_sql_query("select * from PollutionTN", engine)
TX_df = pd.read_sql_query("select * from PollutionTX", engine)
UT_df = pd.read_sql_query("select * from PollutionUT", engine)
VT_df = pd.read_sql_query("select * from PollutionVT", engine)
VA_df = pd.read_sql_query("select * from PollutionVA", engine)
WA_df = pd.read_sql_query("select * from PollutionWA", engine)
WV_df = pd.read_sql_query("select * from PollutionWV", engine)
WI_df = pd.read_sql_query("select * from PollutionWI", engine)
WY_df = pd.read_sql_query("select * from PollutionWY", engine)

TXBlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataTXBlack_or_African_AmericanFemalelarynx", engine)
TXBlack_or_African_AmericanFemaleLUNG=pd.read_sql_query("select * from DataTXBlack_or_African_AmericanFemaleLUNG", engine)
PABlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataPABlack_or_African_AmericanFemalelarynx", engine)
OHBlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataOHBlack_or_African_AmericanFemalelarynx", engine)
NYBlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataNYBlack_or_African_AmericanFemalelarynx", engine)
NYBlack_or_African_AmericanFemaleLUNG=pd.read_sql_query("select * from DataNYBlack_or_African_AmericanFemaleLUNG", engine)
NCBlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataNCBlack_or_African_AmericanFemalelarynx", engine)
MIBlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataMIBlack_or_African_AmericanFemalelarynx", engine)
LABlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataLABlack_or_African_AmericanFemalelarynx", engine)
ILBlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataILBlack_or_African_AmericanFemalelarynx", engine)
GABlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataGABlack_or_African_AmericanFemalelarynx", engine)
FLBlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataFLBlack_or_African_AmericanFemalelarynx", engine)
CABlack_or_African_AmericanFemalelarynx=pd.read_sql_query("select * from DataCABlack_or_African_AmericanFemalelarynx", engine)
WVWhiteFemalelarynx=pd.read_sql_query("select * from DataWVWhiteFemalelarynx", engine)
WVWhiteFemaleLUNG=pd.read_sql_query("select * from DataWVWhiteFemaleLUNG", engine)
WIWhiteFemalelarynx=pd.read_sql_query("select * from DataWIWhiteFemalelarynx", engine)
WIWhiteFemaleLUNG=pd.read_sql_query("select * from DataWIWhiteFemaleLUNG", engine)
WAWhiteFemalelarynx=pd.read_sql_query("select * from DataWAWhiteFemalelarynx", engine)
WAWhiteFemaleLUNG=pd.read_sql_query("select * from DataWAWhiteFemaleLUNG", engine)
VAWhiteFemalelarynx=pd.read_sql_query("select * from DataVAWhiteFemalelarynx", engine)
VAWhiteFemaleLUNG=pd.read_sql_query("select * from DataVAWhiteFemaleLUNG", engine)
TXWhiteFemaleNasal=pd.read_sql_query("select * from DataTXWhiteFemaleNasal", engine)
TXWhiteFemalelarynx=pd.read_sql_query("select * from DataTXWhiteFemalelarynx", engine)
TXWhiteFemaleLUNG=pd.read_sql_query("select * from DataTXWhiteFemaleLUNG", engine)
TNWhiteFemalelarynx=pd.read_sql_query("select * from DataTNWhiteFemalelarynx", engine)
TNWhiteFemaleLUNG=pd.read_sql_query("select * from DataTNWhiteFemaleLUNG", engine)
SCWhiteFemalelarynx=pd.read_sql_query("select * from DataSCWhiteFemalelarynx", engine)
SCWhiteFemaleLUNG=pd.read_sql_query("select * from DataSCWhiteFemaleLUNG", engine)
PAWhiteFemaleNasal=pd.read_sql_query("select * from DataPAWhiteFemaleNasal", engine)
PAWhiteFemalelarynx=pd.read_sql_query("select * from DataPAWhiteFemalelarynx", engine)
PAWhiteFemaleLUNG=pd.read_sql_query("select * from DataPAWhiteFemaleLUNG", engine)
ORWhiteFemalelarynx=pd.read_sql_query("select * from DataORWhiteFemalelarynx", engine)
OKWhiteFemalelarynx=pd.read_sql_query("select * from DataOKWhiteFemalelarynx", engine)
OKWhiteFemaleLUNG=pd.read_sql_query("select * from DataOKWhiteFemaleLUNG", engine)
OHWhiteFemaleNasal=pd.read_sql_query("select * from DataOHWhiteFemaleNasal", engine)
OHWhiteFemalelarynx=pd.read_sql_query("select * from DataOHWhiteFemalelarynx", engine)
OHWhiteFemaleLUNG=pd.read_sql_query("select * from DataOHWhiteFemaleLUNG", engine)
NYWhiteFemaleNasal=pd.read_sql_query("select * from DataNYWhiteFemaleNasal", engine)
NYWhiteFemalelarynx=pd.read_sql_query("select * from DataNYWhiteFemalelarynx", engine)
NYWhiteFemaleLUNG=pd.read_sql_query("select * from DataNYWhiteFemaleLUNG", engine)
NJWhiteFemaleNasal=pd.read_sql_query("select * from DataNJWhiteFemaleNasal", engine)
NJWhiteFemalelarynx=pd.read_sql_query("select * from DataNJWhiteFemalelarynx", engine)
NJWhiteFemaleLUNG=pd.read_sql_query("select * from DataNJWhiteFemaleLUNG", engine)
NCWhiteFemaleNasal=pd.read_sql_query("select * from DataNCWhiteFemaleNasal", engine)
NCWhiteFemalelarynx=pd.read_sql_query("select * from DataNCWhiteFemalelarynx", engine)
NCWhiteFemaleLUNG=pd.read_sql_query("select * from DataNCWhiteFemaleLUNG", engine)
MOWhiteFemalelarynx=pd.read_sql_query("select * from DataMOWhiteFemalelarynx", engine)
MOWhiteFemaleLUNG=pd.read_sql_query("select * from DataMOWhiteFemaleLUNG", engine)
MNWhiteFemalelarynx=pd.read_sql_query("select * from DataMNWhiteFemalelarynx", engine)
MNWhiteFemaleLUNG=pd.read_sql_query("select * from DataMNWhiteFemaleLUNG", engine)
MIWhiteFemaleNasal=pd.read_sql_query("select * from DataMIWhiteFemaleNasal", engine)
MIWhiteFemalelarynx=pd.read_sql_query("select * from DataMIWhiteFemalelarynx", engine)
MIWhiteFemaleLUNG=pd.read_sql_query("select * from DataMIWhiteFemaleLUNG", engine)
MEWhiteFemalelarynx=pd.read_sql_query("select * from DataMEWhiteFemalelarynx", engine)
MDWhiteFemalelarynx=pd.read_sql_query("select * from DataMDWhiteFemalelarynx", engine)
MDWhiteFemaleLUNG=pd.read_sql_query("select * from DataMDWhiteFemaleLUNG", engine)
MAWhiteFemalelarynx=pd.read_sql_query("select * from DataMAWhiteFemalelarynx", engine)
MAWhiteFemaleLUNG=pd.read_sql_query("select * from DataMAWhiteFemaleLUNG", engine)
LAWhiteFemalelarynx=pd.read_sql_query("select * from DataLAWhiteFemalelarynx", engine)
LAWhiteFemaleLUNG=pd.read_sql_query("select * from DataLAWhiteFemaleLUNG", engine)
KYWhiteFemalelarynx=pd.read_sql_query("select * from DataKYWhiteFemalelarynx", engine)
KYWhiteFemaleLUNG=pd.read_sql_query("select * from DataKYWhiteFemaleLUNG", engine)
KSWhiteFemalelarynx=pd.read_sql_query("select * from DataKSWhiteFemalelarynx", engine)
INWhiteFemalelarynx=pd.read_sql_query("select * from DataINWhiteFemalelarynx", engine)
INWhiteFemaleLUNG=pd.read_sql_query("select * from DataINWhiteFemaleLUNG", engine)
ILWhiteFemaleNasal=pd.read_sql_query("select * from DataILWhiteFemaleNasal", engine)
ILWhiteFemalelarynx=pd.read_sql_query("select * from DataILWhiteFemalelarynx", engine)
ILWhiteFemaleLUNG=pd.read_sql_query("select * from DataILWhiteFemaleLUNG", engine)
IAWhiteFemalelarynx=pd.read_sql_query("select * from DataIAWhiteFemalelarynx", engine)
IAWhiteFemaleLUNG=pd.read_sql_query("select * from DataIAWhiteFemaleLUNG", engine)
GAWhiteFemalelarynx=pd.read_sql_query("select * from DataGAWhiteFemalelarynx", engine)
GAWhiteFemaleLUNG=pd.read_sql_query("select * from DataGAWhiteFemaleLUNG", engine)
FLWhiteFemaleNasal=pd.read_sql_query("select * from DataFLWhiteFemaleNasal", engine)
FLWhiteFemalelarynx=pd.read_sql_query("select * from DataFLWhiteFemalelarynx", engine)
FLWhiteFemaleLUNG=pd.read_sql_query("select * from DataFLWhiteFemaleLUNG", engine)
CTWhiteFemalelarynx=pd.read_sql_query("select * from DataCTWhiteFemalelarynx", engine)
CTWhiteFemaleLUNG=pd.read_sql_query("select * from DataCTWhiteFemaleLUNG", engine)
COWhiteFemalelarynx=pd.read_sql_query("select * from DataCOWhiteFemalelarynx", engine)
COWhiteFemaleLUNG=pd.read_sql_query("select * from DataCOWhiteFemaleLUNG", engine)
CAWhiteFemaleNasal=pd.read_sql_query("select * from DataCAWhiteFemaleNasal", engine)
CAWhiteFemalelarynx=pd.read_sql_query("select * from DataCAWhiteFemalelarynx", engine)
CAWhiteFemaleLUNG=pd.read_sql_query("select * from DataCAWhiteFemaleLUNG", engine)
AZWhiteFemalelarynx=pd.read_sql_query("select * from DataAZWhiteFemalelarynx", engine)
AZWhiteFemaleLUNG=pd.read_sql_query("select * from DataAZWhiteFemaleLUNG", engine)
ALWhiteFemalelarynx=pd.read_sql_query("select * from DataALWhiteFemalelarynx", engine)
ALWhiteFemaleLUNG=pd.read_sql_query("select * from DataALWhiteFemaleLUNG", engine)
VABlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataVABlack_or_African_AmericanMalelarynx", engine)
VABlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataVABlack_or_African_AmericanMaleLUNG", engine)
TXBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataTXBlack_or_African_AmericanMalelarynx", engine)
TXBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataTXBlack_or_African_AmericanMaleLUNG", engine)
TNBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataTNBlack_or_African_AmericanMalelarynx", engine)
TNBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataTNBlack_or_African_AmericanMaleLUNG", engine)
SCBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataSCBlack_or_African_AmericanMalelarynx", engine)
SCBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataSCBlack_or_African_AmericanMaleLUNG", engine)
PABlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataPABlack_or_African_AmericanMalelarynx", engine)
PABlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataPABlack_or_African_AmericanMaleLUNG", engine)
OHBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataOHBlack_or_African_AmericanMalelarynx", engine)
OHBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataOHBlack_or_African_AmericanMaleLUNG", engine)
NYBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataNYBlack_or_African_AmericanMalelarynx", engine)
NYBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataNYBlack_or_African_AmericanMaleLUNG", engine)
NJBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataNJBlack_or_African_AmericanMalelarynx", engine)
NJBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataNJBlack_or_African_AmericanMaleLUNG", engine)
NCBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataNCBlack_or_African_AmericanMalelarynx", engine)
NCBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataNCBlack_or_African_AmericanMaleLUNG", engine)
MOBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataMOBlack_or_African_AmericanMalelarynx", engine)
MOBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataMOBlack_or_African_AmericanMaleLUNG", engine)
MIBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataMIBlack_or_African_AmericanMalelarynx", engine)
MIBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataMIBlack_or_African_AmericanMaleLUNG", engine)
MDBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataMDBlack_or_African_AmericanMalelarynx", engine)
MDBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataMDBlack_or_African_AmericanMaleLUNG", engine)
LABlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataLABlack_or_African_AmericanMalelarynx", engine)
LABlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataLABlack_or_African_AmericanMaleLUNG", engine)
KYBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataKYBlack_or_African_AmericanMalelarynx", engine)
INBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataINBlack_or_African_AmericanMalelarynx", engine)
ILBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataILBlack_or_African_AmericanMalelarynx", engine)
ILBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataILBlack_or_African_AmericanMaleLUNG", engine)
GABlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataGABlack_or_African_AmericanMalelarynx", engine)
GABlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataGABlack_or_African_AmericanMaleLUNG", engine)
FLBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataFLBlack_or_African_AmericanMalelarynx", engine)
FLBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataFLBlack_or_African_AmericanMaleLUNG", engine)
CABlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataCABlack_or_African_AmericanMalelarynx", engine)
CABlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataCABlack_or_African_AmericanMaleLUNG", engine)
ALBlack_or_African_AmericanMalelarynx=pd.read_sql_query("select * from DataALBlack_or_African_AmericanMalelarynx", engine)
ALBlack_or_African_AmericanMaleLUNG=pd.read_sql_query("select * from DataALBlack_or_African_AmericanMaleLUNG", engine)
NYAsian_or_Pacific_IslanderMalelarynx=pd.read_sql_query("select * from DataNYAsian_or_Pacific_IslanderMalelarynx", engine)
HIAsian_or_Pacific_IslanderMalelarynx=pd.read_sql_query("select * from DataHIAsian_or_Pacific_IslanderMalelarynx", engine)
CAAsian_or_Pacific_IslanderMalelarynx=pd.read_sql_query("select * from DataCAAsian_or_Pacific_IslanderMalelarynx", engine)
CAAsian_or_Pacific_IslanderMaleLUNG=pd.read_sql_query("select * from DataCAAsian_or_Pacific_IslanderMaleLUNG", engine)
WVWhiteMalelarynx=pd.read_sql_query("select * from DataWVWhiteMalelarynx", engine)
WVWhiteMaleLUNG=pd.read_sql_query("select * from DataWVWhiteMaleLUNG", engine)
WIWhiteMalelarynx=pd.read_sql_query("select * from DataWIWhiteMalelarynx", engine)
WIWhiteMaleLUNG=pd.read_sql_query("select * from DataWIWhiteMaleLUNG", engine)
WAWhiteMaleNasal=pd.read_sql_query("select * from DataWAWhiteMaleNasal", engine)
WAWhiteMalelarynx=pd.read_sql_query("select * from DataWAWhiteMalelarynx", engine)
WAWhiteMaleLUNG=pd.read_sql_query("select * from DataWAWhiteMaleLUNG", engine)
VTWhiteMalelarynx=pd.read_sql_query("select * from DataVTWhiteMalelarynx", engine)
VTWhiteMaleLUNG=pd.read_sql_query("select * from DataVTWhiteMaleLUNG", engine)
VAWhiteMaleNasal=pd.read_sql_query("select * from DataVAWhiteMaleNasal", engine)
VAWhiteMalelarynx=pd.read_sql_query("select * from DataVAWhiteMalelarynx", engine)
VAWhiteMaleLUNG=pd.read_sql_query("select * from DataVAWhiteMaleLUNG", engine)
UTWhiteMalelarynx=pd.read_sql_query("select * from DataUTWhiteMalelarynx", engine)
UTWhiteMaleLUNG=pd.read_sql_query("select * from DataUTWhiteMaleLUNG", engine)
TXWhiteMaleTrach=pd.read_sql_query("select * from DataTXWhiteMaleTrach", engine)
TXWhiteMaleNasal=pd.read_sql_query("select * from DataTXWhiteMaleNasal", engine)
TXWhiteMalelarynx=pd.read_sql_query("select * from DataTXWhiteMalelarynx", engine)
TXWhiteMaleLUNG=pd.read_sql_query("select * from DataTXWhiteMaleLUNG", engine)
TNWhiteMalelarynx=pd.read_sql_query("select * from DataTNWhiteMalelarynx", engine)
TNWhiteMaleLUNG=pd.read_sql_query("select * from DataTNWhiteMaleLUNG", engine)
SCWhiteMalelarynx=pd.read_sql_query("select * from DataSCWhiteMalelarynx", engine)
SCWhiteMaleLUNG=pd.read_sql_query("select * from DataSCWhiteMaleLUNG", engine)
RIWhiteMalelarynx=pd.read_sql_query("select * from DataRIWhiteMalelarynx", engine)
RIWhiteMaleLUNG=pd.read_sql_query("select * from DataRIWhiteMaleLUNG", engine)
PAWhiteMaleNasal=pd.read_sql_query("select * from DataPAWhiteMaleNasal", engine)
PAWhiteMalelarynx=pd.read_sql_query("select * from DataPAWhiteMalelarynx", engine)
PAWhiteMaleLUNG=pd.read_sql_query("select * from DataPAWhiteMaleLUNG", engine)
ORWhiteMalelarynx=pd.read_sql_query("select * from DataORWhiteMalelarynx", engine)
ORWhiteMaleLUNG=pd.read_sql_query("select * from DataORWhiteMaleLUNG", engine)
OKWhiteMalelarynx=pd.read_sql_query("select * from DataOKWhiteMalelarynx", engine)
OKWhiteMaleLUNG=pd.read_sql_query("select * from DataOKWhiteMaleLUNG", engine)
OHWhiteMaleNasal=pd.read_sql_query("select * from DataOHWhiteMaleNasal", engine)
OHWhiteMalelarynx=pd.read_sql_query("select * from DataOHWhiteMalelarynx", engine)
OHWhiteMaleLUNG=pd.read_sql_query("select * from DataOHWhiteMaleLUNG", engine)
NYWhiteMaleTrach=pd.read_sql_query("select * from DataNYWhiteMaleTrach", engine)
NYWhiteMaleNasal=pd.read_sql_query("select * from DataNYWhiteMaleNasal", engine)
NYWhiteMalelarynx=pd.read_sql_query("select * from DataNYWhiteMalelarynx", engine)
NYWhiteMaleLUNG=pd.read_sql_query("select * from DataNYWhiteMaleLUNG", engine)
NVWhiteMalelarynx=pd.read_sql_query("select * from DataNVWhiteMalelarynx", engine)
NVWhiteMaleLUNG=pd.read_sql_query("select * from DataNVWhiteMaleLUNG", engine)
NMWhiteMalelarynx=pd.read_sql_query("select * from DataNMWhiteMalelarynx", engine)
NMWhiteMaleLUNG=pd.read_sql_query("select * from DataNMWhiteMaleLUNG", engine)
NJWhiteMaleNasal=pd.read_sql_query("select * from DataNJWhiteMaleNasal", engine)
NJWhiteMalelarynx=pd.read_sql_query("select * from DataNJWhiteMalelarynx", engine)
NJWhiteMaleLUNG=pd.read_sql_query("select * from DataNJWhiteMaleLUNG", engine)
NHWhiteMalelarynx=pd.read_sql_query("select * from DataNHWhiteMalelarynx", engine)
NHWhiteMaleLUNG=pd.read_sql_query("select * from DataNHWhiteMaleLUNG", engine)
NEWhiteMalelarynx=pd.read_sql_query("select * from DataNEWhiteMalelarynx", engine)
NEWhiteMaleLUNG=pd.read_sql_query("select * from DataNEWhiteMaleLUNG", engine)
NDWhiteMalelarynx=pd.read_sql_query("select * from DataNDWhiteMalelarynx", engine)
NCWhiteMaleNasal=pd.read_sql_query("select * from DataNCWhiteMaleNasal", engine)
NCWhiteMalelarynx=pd.read_sql_query("select * from DataNCWhiteMalelarynx", engine)
NCWhiteMaleLUNG=pd.read_sql_query("select * from DataNCWhiteMaleLUNG", engine)
MTWhiteMalelarynx=pd.read_sql_query("select * from DataMTWhiteMalelarynx", engine)
MOWhiteMalelarynx=pd.read_sql_query("select * from DataMOWhiteMalelarynx", engine)
MOWhiteMaleLUNG=pd.read_sql_query("select * from DataMOWhiteMaleLUNG", engine)
MNWhiteMalelarynx=pd.read_sql_query("select * from DataMNWhiteMalelarynx", engine)
MNWhiteMaleLUNG=pd.read_sql_query("select * from DataMNWhiteMaleLUNG", engine)
MIWhiteMaleNasal=pd.read_sql_query("select * from DataMIWhiteMaleNasal", engine)
MIWhiteMalelarynx=pd.read_sql_query("select * from DataMIWhiteMalelarynx", engine)
MIWhiteMaleLUNG=pd.read_sql_query("select * from DataMIWhiteMaleLUNG", engine)
MEWhiteMalelarynx=pd.read_sql_query("select * from DataMEWhiteMalelarynx", engine)
MEWhiteMaleLUNG=pd.read_sql_query("select * from DataMEWhiteMaleLUNG", engine)
MDWhiteMalelarynx=pd.read_sql_query("select * from DataMDWhiteMalelarynx", engine)
MDWhiteMaleLUNG=pd.read_sql_query("select * from DataMDWhiteMaleLUNG", engine)
MAWhiteMalelarynx=pd.read_sql_query("select * from DataMAWhiteMalelarynx", engine)
MAWhiteMaleLUNG=pd.read_sql_query("select * from DataMAWhiteMaleLUNG", engine)
LAWhiteMalelarynx=pd.read_sql_query("select * from DataLAWhiteMalelarynx", engine)
LAWhiteMaleLUNG=pd.read_sql_query("select * from DataLAWhiteMaleLUNG", engine)
KYWhiteMalelarynx=pd.read_sql_query("select * from DataKYWhiteMalelarynx", engine)
KYWhiteMaleLUNG=pd.read_sql_query("select * from DataKYWhiteMaleLUNG", engine)
KSWhiteMalelarynx=pd.read_sql_query("select * from DataKSWhiteMalelarynx", engine)
KSWhiteMaleLUNG=pd.read_sql_query("select * from DataKSWhiteMaleLUNG", engine)
INWhiteMaleNasal=pd.read_sql_query("select * from DataINWhiteMaleNasal", engine)
INWhiteMalelarynx=pd.read_sql_query("select * from DataINWhiteMalelarynx", engine)
INWhiteMaleLUNG=pd.read_sql_query("select * from DataINWhiteMaleLUNG", engine)
ILWhiteMaleNasal=pd.read_sql_query("select * from DataILWhiteMaleNasal", engine)
ILWhiteMalelarynx=pd.read_sql_query("select * from DataILWhiteMalelarynx", engine)
ILWhiteMaleLUNG=pd.read_sql_query("select * from DataILWhiteMaleLUNG", engine)
IDWhiteMalelarynx=pd.read_sql_query("select * from DataIDWhiteMalelarynx", engine)
IDWhiteMaleLUNG=pd.read_sql_query("select * from DataIDWhiteMaleLUNG", engine)
IAWhiteMalelarynx=pd.read_sql_query("select * from DataIAWhiteMalelarynx", engine)
IAWhiteMaleLUNG=pd.read_sql_query("select * from DataIAWhiteMaleLUNG", engine)
HIWhiteMalelarynx=pd.read_sql_query("select * from DataHIWhiteMalelarynx", engine)
GAWhiteMaleNasal=pd.read_sql_query("select * from DataGAWhiteMaleNasal", engine)
GAWhiteMalelarynx=pd.read_sql_query("select * from DataGAWhiteMalelarynx", engine)
GAWhiteMaleLUNG=pd.read_sql_query("select * from DataGAWhiteMaleLUNG", engine)
FLWhiteMaleTrach=pd.read_sql_query("select * from DataFLWhiteMaleTrach", engine)
FLWhiteMaleNasal=pd.read_sql_query("select * from DataFLWhiteMaleNasal", engine)
FLWhiteMalelarynx=pd.read_sql_query("select * from DataFLWhiteMalelarynx", engine)
FLWhiteMaleLUNG=pd.read_sql_query("select * from DataFLWhiteMaleLUNG", engine)
DEWhiteMalelarynx=pd.read_sql_query("select * from DataDEWhiteMalelarynx", engine)
DEWhiteMaleLUNG=pd.read_sql_query("select * from DataDEWhiteMaleLUNG", engine)
CTWhiteMalelarynx=pd.read_sql_query("select * from DataCTWhiteMalelarynx", engine)
CTWhiteMaleLUNG=pd.read_sql_query("select * from DataCTWhiteMaleLUNG", engine)
COWhiteMalelarynx=pd.read_sql_query("select * from DataCOWhiteMalelarynx", engine)
COWhiteMaleLUNG=pd.read_sql_query("select * from DataCOWhiteMaleLUNG", engine)
CAWhiteMaleTrach=pd.read_sql_query("select * from DataCAWhiteMaleTrach", engine)
CAWhiteMaleNasal=pd.read_sql_query("select * from DataCAWhiteMaleNasal", engine)
CAWhiteMalelarynx=pd.read_sql_query("select * from DataCAWhiteMalelarynx", engine)
CAWhiteMaleLUNG=pd.read_sql_query("select * from DataCAWhiteMaleLUNG", engine)
AZWhiteMalelarynx=pd.read_sql_query("select * from DataAZWhiteMalelarynx", engine)
AZWhiteMaleLUNG=pd.read_sql_query("select * from DataAZWhiteMaleLUNG", engine)
ALWhiteMalelarynx=pd.read_sql_query("select * from DataALWhiteMalelarynx", engine)
ALWhiteMaleLUNG=pd.read_sql_query("select * from DataALWhiteMaleLUNG", engine)

PollutionList = [AK_df, AL_df, AZ_df, AR_df, CA_df, CO_df, CT_df, DE_df, FL_df, GA_df, HI_df, IA_df, ID_df, IL_df, IN_df, KS_df, KY_df, LA_df, MA_df, MD_df, ME_df, MI_df, MN_df, MO_df, MS_df, MT_df, NC_df, ND_df, NE_Df, NH_df, NJ_df, NM_df, NV_df, NY_df, OH_df, OK_df, OR_df, PA_df, PR_df, RI_df, SC_df, SD_df, TN_df, TX_df, UT_df, VA_df, VT_df, WA_df, WI_df, WV_df, WY_df]


stateList = pd.DataFrame({"states":["AK", "AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"]})
print(stateList)

# create route that renders index.html template
@app.route("/")
def home():
    return render_template("index.html")

@app.route("/places")
def places():
    """Return a place names from database."""
    results = stateList['states']

    # Return a list of the column names (sample names)
    return results.to_json(orient = 'records')

 
if __name__ == "__main__":
    app.run(debug=True)